// export const busDeta = [
//   {
//     id:1,
//     startingFrom: "New York",
//     startTime: "08:00 AM",
//     busType: "Sleeper",

//     dropPoint: "Washington D.C.",
//     endTime: "12:00 PM",
//     busNumber: "NYDC101",
//     seatsAvailable: 10,
//     startingDate: "2024-06-15",
//     reachDate: "2024-06-15",
//     price: 50,
//     cuttedPrice: 60,
//     discountPrice: 45,
//     contactNumber: "123-456-7890",
//     operator: "Greyhound",
//     rating: 4.5
//   },
//   {
//     id:2,
//     startingFrom: "Los Angeles",
//     startTime: "09:00 AM",
//     busType: "Semi-Sleeper",
// pPoint: "San Francisco",
//     endTime: "01:00 PM",
//     busNumber: "LASF102",
//     seatsAvailable: 5,
//     startingDate: "2024-06-15",
//     reachDate: "2024-06-15",
//     price: 60,
//     cuttedPrice: 70,
//     discountPrice: 55,
//     contactNumber: "987-654-3210",
//     operator: "Megabus",
//     rating: 4.0
//   },
//   {
//     id:3,
//     startingFrom: "Chicago",
//     startTime: "07:30 AM",
//     busType: "Luxury",

//     dropPoint: "Detroit",
//     endTime: "11:30 AM",
//     busNumber: "CHDET103",
//     seatsAvailable: 15,
//     startingDate: "2024-06-15",
//     reachDate: "2024-06-15",
//     price: 45,
//     cuttedPrice: 55,
//     discountPrice: 40,
//     contactNumber: "321-654-9870",
//     operator: "Greyhound",
//     rating: 4.7
//   },
//   {
//     id:4,
//     startingFrom: "Houston",
//     startTime: "10:00 AM",
//     busType: "Standard",

//     dropPoint: "Dallas",
//     endTime: "02:00 PM",
//     busNumber: "HODAL104",
//     seatsAvailable: 20,
//     startingDate: "2024-06-15",
//     reachDate: "2024-06-15",
//     price: 35,
//     cuttedPrice: 40,
//     discountPrice: 30,
//     contactNumber: "654-321-0987",
//     operator: "Megabus",
//     rating: 3.8
//   },
//   {
//     id:5,
//     startingFrom: "Miami",
//     startTime: "06:00 AM",
//     busType: "Sleeper",

//     dropPoint: "Orlando",
//     endTime: "10:00 AM",
//     busNumber: "MIORL105",
//     seatsAvailable: 8,
//     startingDate: "2024-06-15",
//     reachDate: "2024-06-15",
//     price: 40,
//     cuttedPrice: 50,
//     discountPrice: 35,
//     contactNumber: "789-012-3456",
//     operator: "Greyhound",
//     rating: 4.2
//   },
//   {
//     id:6,
//     startingFrom: "Boston",
//     startTime: "05:00 PM",
//     busType: "Luxury",

//     dropPoint: "New York",
//     endTime: "09:00 PM",
//     busNumber: "BONY106",
//     seatsAvailable: 12,
//     startingDate: "2024-06-15",
//     reachDate: "2024-06-15",
//     price: 55,
//     cuttedPrice: 65,
//     discountPrice: 50,
//     contactNumber: "012-345-6789",
//     operator: "Megabus",
//     rating: 4.6
//   },
//   {
//     id:7,
//     startingFrom: "Seattle",
//     startTime: "07:00 AM",
//     busType: "Standard",

//     dropPoint: "Portland",
//     endTime: "11:00 AM",
//     busNumber: "SEAPOR107",
//     seatsAvailable: 18,
//     startingDate: "2024-06-15",
//     reachDate: "2024-06-15",
//     price: 30,
//     cuttedPrice: 35,
//     discountPrice: 25,
//     contactNumber: "098-765-4321",
//     operator: "Greyhound",
//     rating: 4.1
//   }
// ];

// export const busList = [
//   {
//     id: 1,
//     fromCity: 'Delhi',
//     startTime: '08:00 AM',
//     busType: 'Sleeper',
//     toCity: 'Manali',
//     endTime: '12:00 PM',
//     busNumber: 'DEL-MAN-101',
//     seatsAvailable: 10,
//     startingDate: '2024-06-29',
//     reachDate: '2024-06-29',
//     price: 500,
//     cuttedPrice: 600,
//     discountPrice: 450,
//     contactNumber: '123-456-7890',
//     operator: 'Greyhound',
//     rating: 4.5,
//   },
//   {
//     id: 2,
//     fromCity: 'Delhi',
//     startTime: '09:00 AM',
//     busType: 'Semi-Sleeper',
//     toCity: 'Shimla',
//     endTime: '01:00 PM',
//     busNumber: 'DEL-SHI-102',
//     seatsAvailable: 5,
//     startingDate: '2024-06-29',
//     reachDate: '2024-06-29',
//     price: 600,
//     cuttedPrice: 700,
//     discountPrice: 550,
//     contactNumber: '987-654-3210',
//     operator: 'Megabus',
//     rating: 4.0,
//   },
//   {
//     id: 3,
//     fromCity: 'Mumbai',
//     startTime: '07:30 AM',
//     busType: 'Luxury',
//     toCity: 'Pune',
//     endTime: '11:30 AM',
//     busNumber: 'MUM-PUN-103',
//     seatsAvailable: 15,
//     startingDate: '2024-06-29',
//     reachDate: '2024-06-29',
//     price: 450,
//     cuttedPrice: 550,
//     discountPrice: 400,
//     contactNumber: '321-654-9870',
//     operator: 'Greyhound',
//     rating: 4.7,
//   },
//   {
//     id: 4,
//     fromCity: 'Bangalore',
//     startTime: '10:00 AM',
//     busType: 'Standard',
//     toCity: 'Mysore',
//     endTime: '02:00 PM',
//     busNumber: 'BAN-MYS-104',
//     seatsAvailable: 20,
//     startingDate: '2024-06-29',
//     reachDate: '2024-06-29',
//     price: 350,
//     cuttedPrice: 400,
//     discountPrice: 300,
//     contactNumber: '654-321-0987',
//     operator: 'Megabus',
//     rating: 3.8,
//   },
//   {
//     id: 5,
//     fromCity: 'Chennai',
//     startTime: '06:00 AM',
//     busType: 'Sleeper',
//     toCity: 'Coimbatore',
//     endTime: '10:00 AM',
//     busNumber: 'CHE-COI-105',
//     seatsAvailable: 8,
//     startingDate: '2024-06-29',
//     reachDate: '2024-06-29',
//     price: 400,
//     cuttedPrice: 500,
//     discountPrice: 350,
//     contactNumber: '789-012-3456',
//     operator: 'Greyhound',
//     rating: 4.2,
//   },
//   {
//     id: 6,
//     fromCity: 'Hyderabad',
//     startTime: '05:00 PM',
//     busType: 'Luxury',
//     toCity: 'Vijayawada',
//     endTime: '09:00 PM',
//     busNumber: 'HYD-VIJ-106',
//     seatsAvailable: 12,
//     startingDate: '2024-06-29',
//     reachDate: '2024-06-29',
//     price: 550,
//     cuttedPrice: 650,
//     discountPrice: 500,
//     contactNumber: '012-345-6789',
//     operator: 'Megabus',
//     rating: 4.6,
//   },
//   {
//     id: 7,
//     fromCity: 'Kolkata',
//     startTime: '07:00 AM',
//     busType: 'Standard',
//     toCity: 'Durgapur',
//     endTime: '11:00 AM',
//     busNumber: 'KOL-DUR-107',
//     seatsAvailable: 18,
//     startingDate: '2024-06-29',
//     reachDate: '2024-06-29',
//     price: 300,
//     cuttedPrice: 350,
//     discountPrice: 250,
//     contactNumber: '098-765-4321',
//     operator: 'Greyhound',
//     rating: 4.1,
//   },
//   {
//     id: 8,
//     fromCity: 'Delhi',
//     startTime: '10:00 AM',
//     busType: 'Sleeper',
//     toCity: 'Shimla',
//     endTime: '02:00 PM',
//     busNumber: 'DEL-Shi-101',
//     seatsAvailable: 10,
//     startingDate: '2024-06-29',
//     reachDate: '2024-06-29',
//     price: 520,
//     cuttedPrice: 700,
//     discountPrice: 450,
//     contactNumber: '123-456-7890',
//     operator: 'Ninjajuk',
//     rating: 4.5,
//   },
// ];

export const busList = [
  {
    id: 1,
    fromCity: "Delhi",
    startTime: "08:00 AM",
    busType: "Sleeper",
    toCity: "Manali",
    endTime: "12:00 PM",
    busNumber: "DEL-MAN-101",
    seatsAvailable: 10,
    startingDate: "2024-06-29",
    reachDate: "2024-06-29",
    price: 500,
    cuttedPrice: 600,
    discountPrice: 450,
    contactNumber: "123-456-7890",
    operator: "Greyhound",
    rating: 4.5,
    seatLayout: [
      [
        { status: 0, id: "1A", price: 10 },
        { status: 0, id: "1B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "1C", price: 10 },
        { status: 0, id: "1D", price: 12 },
      ],
      [
        { status: 0, id: "2A", price: 10 },
        { status: 0, id: "2B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "2C", price: 10 },
        { status: 0, id: "2D", price: 12 },
      ],
      [
        { status: 0, id: "3A", price: 10 },
        { status: 0, id: "3B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "3C", price: 10 },
        { status: 0, id: "3D", price: 12 },
      ],
      [
        { status: 0, id: "4A", price: 10 },
        { status: 0, id: "4B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "4C", price: 10 },
        { status: 0, id: "4D", price: 12 },
      ],
      [
        { status: 0, id: "5A", price: 10 },
        { status: 0, id: "5B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "5C", price: 10 },
        { status: 0, id: "5D", price: 12 },
      ],
      [
        { status: 0, id: "6A", price: 10 },
        { status: 0, id: "6B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "6C", price: 10 },
        { status: 0, id: "6D", price: 12 },
      ],
      [
        { status: 0, id: "7A", price: 10 },
        { status: 0, id: "7B", price: 12 },
        { status: 0, id: "7C", price: 10 },
        { status: 0, id: "7D", price: 12 },
        { status: 0, id: "7E", price: 15 },
      ],
      [
        { status: 0, id: "7A", price: 10 },
        { status: 0, id: "7B", price: 12 },
        { status: 0, id: "7C", price: 10 },
        { status: 0, id: "7D", price: 12 },
        { status: 0, id: "7E", price: 15 },
      ],
    ],
  },
  {
    id: 2,
    fromCity: "Delhi",
    startTime: "09:00 AM",
    busType: "Semi-Sleeper",
    toCity: "Shimla",
    endTime: "01:00 PM",
    busNumber: "DEL-SHI-102",
    seatsAvailable: 5,
    startingDate: "2024-06-29",
    reachDate: "2024-06-29",
    price: 600,
    cuttedPrice: 700,
    discountPrice: 550,
    contactNumber: "987-654-3210",
    operator: "Megabus",
    rating: 4.0,
    seatLayout: [
      [
        { status: 0, id: "1A", price: 10 },
        { status: 0, id: "1B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "1C", price: 10 },
        { status: 0, id: "1D", price: 12 },
      ],
      [
        { status: 0, id: "2A", price: 10 },
        { status: 0, id: "2B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "2C", price: 10 },
        { status: 0, id: "2D", price: 12 },
      ],
      [
        { status: 0, id: "3A", price: 10 },
        { status: 0, id: "3B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "3C", price: 10 },
        { status: 0, id: "3D", price: 12 },
      ],
      [
        { status: 0, id: "4A", price: 10 },
        { status: 0, id: "4B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "4C", price: 10 },
        { status: 0, id: "4D", price: 12 },
      ],
      [
        { status: 0, id: "5A", price: 10 },
        { status: 0, id: "5B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "5C", price: 10 },
        { status: 0, id: "5D", price: 12 },
      ],
      [
        { status: 0, id: "7A", price: 10 },
        { status: 0, id: "7B", price: 12 },
        { status: 0, id: "7C", price: 10 },
        { status: 0, id: "7D", price: 12 },
        { status: 0, id: "7E", price: 15 },
      ],
    ],
  },
  {
    id: 3,
    fromCity: "Mumbai",
    startTime: "07:30 AM",
    busType: "Luxury",
    toCity: "Pune",
    endTime: "11:30 AM",
    busNumber: "MUM-PUN-103",
    seatsAvailable: 15,
    startingDate: "2024-06-29",
    reachDate: "2024-06-29",
    price: 450,
    cuttedPrice: 550,
    discountPrice: 400,
    contactNumber: "321-654-9870",
    operator: "Greyhound",
    rating: 4.7,
    seatLayout: [
      [
        { status: 0, id: "1A", price: 10 },
        { status: 0, id: "1B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "1C", price: 10 },
        { status: 0, id: "1D", price: 12 },
      ],
      [
        { status: 0, id: "2A", price: 10 },
        { status: 0, id: "2B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "2C", price: 10 },
        { status: 0, id: "2D", price: 12 },
      ],
      [
        { status: 0, id: "3A", price: 10 },
        { status: 0, id: "3B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "3C", price: 10 },
        { status: 0, id: "3D", price: 12 },
      ],
      [
        { status: 0, id: "4A", price: 10 },
        { status: 0, id: "4B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "4C", price: 10 },
        { status: 0, id: "4D", price: 12 },
      ],
      [
        { status: 0, id: "5A", price: 10 },
        { status: 0, id: "5B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "5C", price: 10 },
        { status: 0, id: "5D", price: 12 },
      ],
      [
        { status: 0, id: "6A", price: 10 },
        { status: 0, id: "6B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "6C", price: 10 },
        { status: 0, id: "6D", price: 12 },
      ],
    ],
  },
  {
    id: 4,
    fromCity: "Bangalore",
    startTime: "10:00 AM",
    busType: "Standard",
    toCity: "Mysore",
    endTime: "02:00 PM",
    busNumber: "BAN-MYS-104",
    seatsAvailable: 20,
    startingDate: "2024-06-29",
    reachDate: "2024-06-29",
    price: 350,
    cuttedPrice: 400,
    discountPrice: 300,
    contactNumber: "654-321-0987",
    operator: "Megabus",
    rating: 3.8,
    seatLayout: [
      [
        { status: 0, id: "1A", price: 10 },
        { status: 0, id: "1B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "1C", price: 10 },
        { status: 0, id: "1D", price: 12 },
      ],
      [
        { status: 0, id: "2A", price: 10 },
        { status: 0, id: "2B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "2C", price: 10 },
        { status: 0, id: "2D", price: 12 },
      ],
      [
        { status: 0, id: "3A", price: 10 },
        { status: 0, id: "3B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "3C", price: 10 },
        { status: 0, id: "3D", price: 12 },
      ],
      [
        { status: 0, id: "4A", price: 10 },
        { status: 0, id: "4B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "4C", price: 10 },
        { status: 0, id: "4D", price: 12 },
      ],
      [
        { status: 0, id: "5A", price: 10 },
        { status: 0, id: "5B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "5C", price: 10 },
        { status: 0, id: "5D", price: 12 },
      ],
      [
        { status: 0, id: "6A", price: 10 },
        { status: 0, id: "6B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "6C", price: 10 },
        { status: 0, id: "6D", price: 12 },
      ],
      [
        { status: 0, id: "7A", price: 10 },
        { status: 0, id: "7B", price: 12 },
        { status: 0, id: "7C", price: 10 },
        { status: 0, id: "7D", price: 12 },
        { status: 0, id: "7E", price: 15 },
      ],
    ],
  },
  {
    id: 5,
    fromCity: "Chennai",
    startTime: "06:00 AM",
    busType: "Sleeper",
    toCity: "Coimbatore",
    endTime: "10:00 AM",
    busNumber: "CHE-COI-105",
    seatsAvailable: 8,
    startingDate: "2024-06-29",
    reachDate: "2024-06-29",
    price: 400,
    cuttedPrice: 500,
    discountPrice: 350,
    contactNumber: "789-012-3456",
    operator: "Greyhound",
    rating: 4.2,
    seatLayout: [
      [
        { status: 0, id: "1A", price: 10 },
        { status: 0, id: "1B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "1C", price: 10 },
        { status: 0, id: "1D", price: 12 },
      ],
      [
        { status: 0, id: "2A", price: 10 },
        { status: 0, id: "2B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "2C", price: 10 },
        { status: 0, id: "2D", price: 12 },
      ],
      [
        { status: 0, id: "3A", price: 10 },
        { status: 0, id: "3B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "3C", price: 10 },
        { status: 0, id: "3D", price: 12 },
      ],
      [
        { status: 0, id: "4A", price: 10 },
        { status: 0, id: "4B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "4C", price: 10 },
        { status: 0, id: "4D", price: 12 },
      ],
      [
        { status: 0, id: "5A", price: 10 },
        { status: 0, id: "5B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "5C", price: 10 },
        { status: 0, id: "5D", price: 12 },
      ],
    ],
  },
  {
    id: 6,
    fromCity: "Hyderabad",
    startTime: "05:00 PM",
    busType: "Luxury",
    toCity: "Vijayawada",
    endTime: "09:00 PM",
    busNumber: "HYD-VIJ-106",
    seatsAvailable: 12,
    startingDate: "2024-06-29",
    reachDate: "2024-06-29",
    price: 550,
    cuttedPrice: 650,
    discountPrice: 500,
    contactNumber: "012-345-6789",
    operator: "Megabus",
    rating: 4.6,
    seatLayout: [
      [
        { status: 0, id: "1A", price: 10 },
        { status: 0, id: "1B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "1C", price: 10 },
        { status: 0, id: "1D", price: 12 },
      ],
      [
        { status: 0, id: "2A", price: 10 },
        { status: 0, id: "2B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "2C", price: 10 },
        { status: 0, id: "2D", price: 12 },
      ],
      [
        { status: 0, id: "3A", price: 10 },
        { status: 0, id: "3B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "3C", price: 10 },
        { status: 0, id: "3D", price: 12 },
      ],
      [
        { status: 0, id: "4A", price: 10 },
        { status: 0, id: "4B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "4C", price: 10 },
        { status: 0, id: "4D", price: 12 },
      ],
      [
        { status: 0, id: "5A", price: 10 },
        { status: 0, id: "5B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "5C", price: 10 },
        { status: 0, id: "5D", price: 12 },
      ],
      [
        { status: 0, id: "6A", price: 10 },
        { status: 0, id: "6B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "6C", price: 10 },
        { status: 0, id: "6D", price: 12 },
      ],
      [
        { status: 0, id: "7A", price: 10 },
        { status: 0, id: "7B", price: 12 },
        { status: 0, id: "7C", price: 10 },
        { status: 0, id: "7D", price: 12 },
        { status: 0, id: "7E", price: 15 },
      ],
    ],
  },
  {
    id: 7,
    fromCity: "Delhi",
    startTime: "09:00 AM",
    busType: "Semi-Sleeper",
    toCity: "Shimla",
    endTime: "01:00 PM",
    busNumber: "DEL-SHI-2025",
    seatsAvailable: 5,
    startingDate: "2024-06-29",
    reachDate: "2024-06-29",
    price: 600,
    cuttedPrice: 700,
    discountPrice: 550,
    contactNumber: "987-654-3210",
    operator: "StarBus",
    rating: 4.0,
    seatLayout: [
      [
        { status: 0, id: "1A", price: 10 },
        { status: 0, id: "1B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "1C", price: 10 },
        { status: 0, id: "1D", price: 12 },
      ],
      [
        { status: 0, id: "2A", price: 10 },
        { status: 0, id: "2B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "2C", price: 10 },
        { status: 0, id: "2D", price: 12 },
      ],
      [
        { status: 0, id: "3A", price: 10 },
        { status: 0, id: "3B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "3C", price: 10 },
        { status: 0, id: "3D", price: 12 },
      ],
      [
        { status: 0, id: "4A", price: 10 },
        { status: 0, id: "4B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "4C", price: 10 },
        { status: 0, id: "4D", price: 12 },
      ],
      [
        { status: 0, id: "5A", price: 10 },
        { status: 0, id: "5B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "5C", price: 10 },
        { status: 0, id: "5D", price: 12 },
      ],
      [
        { status: 0, id: "6A", price: 10 },
        { status: 0, id: "6B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "6C", price: 10 },
        { status: 0, id: "6D", price: 12 },
      ],
      [
        { status: 0, id: "7A", price: 10 },
        { status: 0, id: "7B", price: 12 },
        { status: 0, id: "7C", price: 10 },
        { status: 0, id: "7D", price: 12 },
        { status: 0, id: "7E", price: 15 },
      ],
    ],
  },
  {
    id: 8,
    fromCity: "Delhi",
    startTime: "09:00 AM",
    busType: "Semi-Sleeper",
    toCity: "Shimla",
    endTime: "01:00 PM",
    busNumber: "DEL-SHI-2025",
    seatsAvailable: 5,
    startingDate: "2024-06-29",
    reachDate: "2024-06-29",
    price: 650,
    cuttedPrice: 750,
    discountPrice: 550,
    contactNumber: "987-654-3210",
    operator: "Volvo",
    rating: 4.0,
    seatLayout: [
      [
        { status: 0, id: "1A", price: 10 },
        { status: 0, id: "1B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "1C", price: 10 },
        { status: 0, id: "1D", price: 12 },
        { status: 0, id: "1E", price: 120 },
      ],
      [
        { status: 0, id: "2A", price: 10 },
        { status: 0, id: "2B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "2C", price: 10 },
        { status: 0, id: "2D", price: 12 },
        { status: 0, id: "2E", price: 120 },
      ],
      [
        { status: 0, id: "3A", price: 10 },
        { status: 0, id: "3B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "3C", price: 10 },
        { status: 0, id: "3D", price: 12 },
        { status: 0, id: "3E", price: 120 },
      ],
      [
        { status: 0, id: "4A", price: 10 },
        { status: 0, id: "4B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "4C", price: 10 },
        { status: 0, id: "4D", price: 12 },
        { status: 0, id: "4E", price: 120 },
      ],
      [
        { status: 0, id: "5A", price: 10 },
        { status: 0, id: "5B", price: 12 },
        { status: -1, id: "", price: 0 },
        { status: 0, id: "5C", price: 10 },
        { status: 0, id: "5D", price: 12 },
        { status: 0, id: "5E", price: 120 },
      ],
      // [
      //   { status: 0, id: "6A", price: 10 },
      //   { status: 0, id: "6B", price: 12 },
      //   { status: -1, id: "", price: 0 },
      //   { status: 0, id: "6C", price: 10 },
      //   { status: 0, id: "6D", price: 12 },

      // ],
      [
        { status: 0, id: "7A", price: 10 },
        { status: 0, id: "7B", price: 12 },
        { status: 0, id: "7C", price: 10 },
        { status: 0, id: "7D", price: 12 },
        { status: 0, id: "7E", price: 15 },
        { status: 0, id: "1F", price: 120 },
      ],
    ],
  },
];
