export const userData = [
    {
      id: 1,
      name: "John Doe",
      email: "john.doe@example.com",
      phone: "123-456-7890",
      address: "123 Main St, Anytown, USA",
      role: "Admin",
    },
    {
      id: 2,
      name: "Jane Smith",
      email: "jane.smith@example.com",
      phone: "234-567-8901",
      address: "456 Elm St, Othertown, USA",
      role: "User",
    },
    {
      id: 3,
      name: "Alice Johnson",
      email: "alice.johnson@example.com",
      phone: "345-678-9012",
      address: "789 Oak St, Sometown, USA",
      role: "User",
    },
    {
      id: 4,
      name: "Bob Brown",
      email: "bob.brown@example.com",
      phone: "456-789-0123",
      address: "101 Maple St, Anycity, USA",
      role: "Moderator",
    },
    {
      id: 5,
      name: "Charlie Davis",
      email: "charlie.davis@example.com",
      phone: "567-890-1234",
      address: "202 Pine St, Othercity, USA",
      role: "User",
    },
    {
      id: 6,
      name: "Diana Evans",
      email: "diana.evans@example.com",
      phone: "678-901-2345",
      address: "303 Cedar St, Somecity, USA",
      role: "Admin",
    },
    {
      id: 7,
      name: "Frank Green",
      email: "frank.green@example.com",
      phone: "789-012-3456",
      address: "404 Birch St, Anyville, USA",
      role: "User",
    },
    {
      id: 8,
      name: "Grace Harris",
      email: "grace.harris@example.com",
      phone: "890-123-4567",
      address: "505 Spruce St, Otherville, USA",
      role: "User",
    },
    {
      id: 9,
      name: "Hank Ingram",
      email: "hank.ingram@example.com",
      phone: "901-234-5678",
      address: "606 Fir St, Someville, USA",
      role: "Moderator",
    },
    {
      id: 10,
      name: "Ivy Jackson",
      email: "ivy.jackson@example.com",
      phone: "012-345-6789",
      address: "707 Willow St, Anyplace, USA",
      role: "User",
    },
  ];

  export default userData;
  
  export const column1Header=['name','email','phone','address','role']
  export const cities = [
    "Aizawl",
    "Kolasib",
    "Silchar",
    "Shillong",
    "Guwahati",
    "Dibrugarh",
    "Itanagar",
    "Tawang",
    "Ziro",
    "Bomdila",
    "Pasighat",
    "Along",
    "Tezu",
    "Roing",
    "Namsai",
    "Changlang",
    "Khonsa",
    "Yingkiong",
    "Daporijo",
    "Anini",
    "Seppa",
    "Koloriang",
    "Pangin",
    "Mechuka",
    "Tuting",
    "Basar",
    "Hawai",
    "Longding",
    "Ruksin",
    "Deomali",
    "Kanubari",
    "Delhi"
  ];
  
  