export const VehicleData = [
  {
    id: 1,
    vehicleType: "SUV",
    title: "Vehicle1",
    vehicleNumber: "MH12AB3457",
    model: "Mahindra Bolero Neo",
    seatingCapacity: "7",
    driverName: "Ravi Kumar",
    driverContact: "9876543210",
    ownerName: "Amit Sharma",
    ownerNumber: "9876543211",
    isAvailable: true,
    description: "Spacious and comfortable SUV perfect for long trips.",
    img: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Mahindra/Bolero-Neo/10766/1690267562292/front-left-side-47.jpg",
    link: "",
    btnText: "Book vehicle",
  },
  {
    id: 2,
    vehicleType: "Sedan",
    title: "Vehicle2",
    vehicleNumber: "DL10CD7890",
    model: "Honda City",
    seatingCapacity: "5",
    driverName: "Vikram Singh",
    driverContact: "9876543212",
    ownerName: "Rajesh Verma",
    ownerNumber: "9876543213",
    isAvailable: false,
    description: "Elegant sedan ideal for city commutes.",
    img: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Honda/City/1690267562292/front-left-side-47.jpg",
    link: "",
    btnText: "Book vehicle",
  },
  {
    id: 3,
    vehicleType: "Hatchback",
    title: "Vehicle3",
    vehicleNumber: "KA03AB4567",
    model: "Maruti Suzuki Swift",
    seatingCapacity: "5",
    driverName: "Suresh Patel",
    driverContact: "9876543214",
    ownerName: "Nikhil Mehta",
    ownerNumber: "9876543215",
    isAvailable: true,
    description: "Compact hatchback, perfect for small families.",
    img: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Maruti/Swift/1690267562292/front-left-side-47.jpg",
    link: "",
    btnText: "Book vehicle",
  },
  {
    id: 4,
    vehicleType: "Minivan",
    title: "Vehicle4",
    vehicleNumber: "TN07CD1234",
    model: "Toyota Innova Crysta",
    seatingCapacity: "8",
    driverName: "Mohan Kumar",
    driverContact: "9876543216",
    ownerName: "Praveen Gupta",
    ownerNumber: "9876543217",
    isAvailable: true,
    description: "Spacious minivan, ideal for large groups.",
    img: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Toyota/Innova-Crysta/1690267562292/front-left-side-47.jpg",
    link: "",
    btnText: "Book vehicle",
  },
  {
    id: 5,
    vehicleType: "Truck",
    title: "Vehicle5",
    vehicleNumber: "MH14EF5678",
    model: "Tata Ace",
    seatingCapacity: "2",
    driverName: "Hari Prasad",
    driverContact: "9876543218",
    ownerName: "Sunil Agarwal",
    ownerNumber: "9876543219",
    isAvailable: false,
    description: "Small truck suitable for transporting goods.",
    img: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Tata/Ace/1690267562292/front-left-side-47.jpg",
    link: "",
    btnText: "Book vehicle",
  },
  {
    id: 6,
    vehicleType: "Bus",
    title: "Vehicle6",
    vehicleNumber: "RJ19GH6789",
    model: "Ashok Leyland",
    seatingCapacity: "50",
    driverName: "Ganesh Yadav",
    driverContact: "9876543220",
    ownerName: "Manoj Singh",
    ownerNumber: "9876543221",
    isAvailable: true,
    description: "Large bus, suitable for group tours and events.",
    img: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Ashok-Leyland/Bus/1690267562292/front-left-side-47.jpg",
    link: "",
    btnText: "Book vehicle",
  },
  {
    id: 7,
    vehicleType: "Pickup Truck",
    title: "Vehicle7",
    vehicleNumber: "GJ01IJ3456",
    model: "Mahindra Scorpio Getaway",
    seatingCapacity: "4",
    driverName: "Ramesh Patel",
    driverContact: "9876543222",
    ownerName: "Vikas Thakur",
    ownerNumber: "9876543223",
    isAvailable: true,
    description: "Rugged pickup truck for heavy-duty transport.",
    img: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Mahindra/Scorpio-Getaway/1690267562292/front-left-side-47.jpg",
    link: "",
    btnText: "Book vehicle",
  },
  {
    id: 8,
    vehicleType: "Convertible",
    title: "Vehicle8",
    vehicleNumber: "UP32KL9876",
    model: "BMW Z4",
    seatingCapacity: "2",
    driverName: "Vijay Kumar",
    driverContact: "9876543224",
    ownerName: "Arun Khanna",
    ownerNumber: "9876543225",
    isAvailable: false,
    description: "Luxurious convertible for special occasions.",
    img: "https://stimg.cardekho.com/images/carexteriorimages/930x620/BMW/Z4/1690267562292/front-left-side-47.jpg",
    link: "",
    btnText: "Book vehicle",
  },
  {
    id: 9,
    vehicleType: "Luxury Sedan",
    title: "Vehicle9",
    vehicleNumber: "DL05MN1234",
    model: "Mercedes-Benz S-Class",
    seatingCapacity: "5",
    driverName: "Ashok Gupta",
    driverContact: "9876543226",
    ownerName: "Karan Kapoor",
    ownerNumber: "9876543227",
    isAvailable: true,
    description: "Premium luxury sedan for VIP clients.",
    img: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Mercedes-Benz/S-Class/1690267562292/front-left-side-47.jpg",
    link: "",
    btnText: "Book vehicle",
  },
  {
    id: 10,
    vehicleType: "Electric",
    title: "Vehicle10",
    vehicleNumber: "MH01PQ4567",
    model: "Tesla Model 3",
    seatingCapacity: "5",
    driverName: "Rajesh Iyer",
    driverContact: "9876543228",
    ownerName: "Sanjay Rao",
    ownerNumber: "9876543229",
    isAvailable: true,
    description: "Eco-friendly electric vehicle with advanced features.",
    img: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Tesla/Model-3/1690267562292/front-left-side-47.jpg",
    link: "",
    btnText: "Book vehicle",
  },
  {
    id: 11,
    vehicleType: "Electric",
    title: "Vehicle10",
    vehicleNumber: "MH01PQ4567",
    model: "Tesla Model 3",
    seatingCapacity: "5",
    driverName: "Rajesh Iyer",
    driverContact: "9876543228",
    ownerName: "Sanjay Rao",
    ownerNumber: "9876543229",
    isAvailable: true,
    description: "Eco-friendly electric vehicle with advanced features.",
    img: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Tesla/Model-3/1690267562292/front-left-side-47.jpg",
    link: "",
    btnText: "Book vehicle",
  },
  {
    id: 12,
    vehicleType: "Electric",
    title: "Vehicle10",
    vehicleNumber: "MH01PQ4567",
    model: "Tesla Model 3",
    seatingCapacity: "5",
    driverName: "Rajesh Iyer",
    driverContact: "9876543228",
    ownerName: "Sanjay Rao",
    ownerNumber: "9876543229",
    isAvailable: true,
    description: "Eco-friendly electric vehicle with advanced features.",
    img: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Tesla/Model-3/1690267562292/front-left-side-47.jpg",
    link: "",
    btnText: "Book vehicle",
  },
  {
    id: 13,
    vehicleType: "Electric",
    title: "Vehicle10",
    vehicleNumber: "MH01PQ4567",
    model: "Tesla Model 3",
    seatingCapacity: "5",
    driverName: "Rajesh Iyer",
    driverContact: "9876543228",
    ownerName: "Sanjay Rao",
    ownerNumber: "9876543229",
    isAvailable: true,
    description: "Eco-friendly electric vehicle with advanced features.",
    img: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Tesla/Model-3/1690267562292/front-left-side-47.jpg",
    link: "",
    btnText: "Book vehicle",
  },
];
